{ "actor": [{	
"PersonsID":"1",
"CastingSygnature":"AN234432",
"PersonStatusDVID":"2",
"PersonStatusName":"Wprowadzana",
"LastName":"Kośiński",
"FirstName":"janusz",
"Phone":"49384493029",
"email":"testpwp@test.pl",
"Street":"testowa",
"Building":"2",
"Flat":"5B",
"City":"testowo",
"Voivodeship": "małopolskie",
"Country":"Polska",
"Gender":"M",
"DateOfBirdth":"1988-04-09",
"Nationality":"polska",
"OccupationInfo":"świetna praca",
"CurrentJobInfo":"kolonia",
"Height":"189",
"Weight":"89",
"ChestCircumference":"66",
"WaistCircumference":"62",
"HipCircumference":"80",
"RODOStatusDVID":"1",
"RODOStatusName":"Zgoda udzielona",
"MediaRightsGranted":"1",
"DefaultPictureFileName":"../img/people.jpg",
"ExternalMediaLinks":"http://aden.pl",
"ActorCategoriesAgregation":"punk,świr,nieboszczyk",
"Canceled":"0",
"CreationDate":"2019-04-01",
"WhoCreated":"taki tam",
"DateOfChange":"2019-04-01",
"WhoChanged":"takitu",
"OccupationCategory":"Tancerz",
"HairColor":"blond",
"EyeColor":"niebieskie",
"SpecialFeatures":"blizna na policzku",
"Skils":"Jazda konna",
"Languages":"chiński",
"DrivingLicence":"A",
"Gender":"M",
"Education":"wyższe",
"ArtisticExperience":"",
"ClothingSize":"36",
"ShoeSize":"42",
"ActorCategory":"Ofiara losu",
"ActingSkillsGrade":"2",
"PersonStatus":"nowy",
"OrderStatus":"nowy",
"RoleStatus":"nowy",
"RODOStatus":"nowy"
}]}